# Generated by Django 4.2.7 on 2023-11-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_team_localizacao_team_isonseriea'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='localizacao',
            field=models.CharField(default='Sao Paulo', max_length=100),
            preserve_default=False,
        ),
    ]
